# Generated by Django 4.1.11 on 2024-02-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='FeedbackData',
        ),
        migrations.DeleteModel(
            name='QuickFormData',
        ),
    ]
